{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:01:08.826Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:01:08.829Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:01:08.829Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:03:19.598Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:03:19.602Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:03:19.602Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:05:30.846Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:05:30.851Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:05:30.851Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:07:42.181Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:07:42.188Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:07:42.188Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:09:53.653Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:09:53.655Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:09:53.656Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:12:04.309Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:12:04.312Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:12:04.312Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:14:15.150Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:14:15.155Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:14:15.155Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:16:28.225Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:16:28.231Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:16:28.232Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:18:40.463Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:18:40.469Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:18:40.469Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:20:51.776Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:20:51.780Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:20:51.780Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:23:02.597Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:23:02.600Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:23:02.601Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:25:13.480Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:25:13.485Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:25:13.486Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:27:26.973Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:27:26.977Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:27:26.977Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:29:37.885Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:29:37.889Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:29:37.889Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:31:49.123Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:31:49.131Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:31:49.131Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:34:00.118Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:34:00.124Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-18T00:34:00.124Z"}
