{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:18:18.751Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:18:18.754Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:18:18.754Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:21:00.556Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:21:00.565Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:21:00.565Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:37:00.280Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:37:00.286Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:37:00.287Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:39:40.214Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:39:40.218Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:39:40.218Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:39:50.258Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:39:50.269Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:39:50.269Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:51:23.637Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:51:23.642Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:51:23.643Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:52:12.767Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:52:12.778Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:52:12.778Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:52:21.830Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:52:21.840Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:52:21.841Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:52:52.493Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:52:52.498Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:52:52.499Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:54:49.699Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:54:49.708Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:54:49.709Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:55:18.180Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:55:18.186Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:55:18.187Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:55:31.903Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:55:31.919Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T08:55:31.919Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T09:55:04.011Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T09:55:04.014Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connect ECONNREFUSED 116.196.95.223:27017]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:182:13)\n    at Pool.EventEmitter.emit (domain.js:442:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:273:13)\n    at Connection.emit (events.js:182:13)\n    at Connection.EventEmitter.emit (domain.js:442:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:245:50)\n    at Object.onceWrapper (events.js:273:13)\n    at Socket.emit (events.js:182:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2018-12-04T09:55:04.022Z"}
