{"level":"info","message":"Client disconnect: undefined","timestamp":"2019-12-09T22:04:16.333Z"}
{"level":"error","message":"Can not find client undefined on disconnect","timestamp":"2019-12-09T22:04:16.336Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:04:45.202Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:04:45.203Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:04:45.203Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:06:55.569Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:06:55.572Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:06:55.572Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:09:06.622Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:09:06.627Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:09:06.628Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:11:16.782Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:11:16.785Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:11:16.785Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:13:27.199Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:13:27.202Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:13:27.202Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:15:37.426Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:15:37.430Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:15:37.431Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:17:47.672Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:17:47.674Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:17:47.675Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:19:57.790Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:19:57.793Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:19:57.794Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:22:08.721Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:22:08.724Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:22:08.725Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:24:18.854Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:24:18.858Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:24:18.858Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:26:28.908Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:26:28.912Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:26:28.913Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:28:38.916Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:28:38.918Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:28:38.919Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:30:49.118Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:30:49.121Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:30:49.121Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:33:00.107Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:33:00.110Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:33:00.110Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:35:10.159Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:35:10.163Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:35:10.163Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:37:20.495Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:37:20.498Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:37:20.499Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:39:30.672Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:39:30.677Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:39:30.678Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:41:41.164Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:41:41.167Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:41:41.168Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:43:51.579Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:43:51.582Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:43:51.583Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:46:02.327Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:46:02.330Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:46:02.330Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:48:12.558Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:48:12.561Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:48:12.561Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:50:22.839Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:50:22.842Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:50:22.842Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:52:33.115Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:52:33.119Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:52:33.120Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:54:43.184Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:54:43.188Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:54:43.188Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:56:53.508Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:56:53.511Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:56:53.511Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:59:04.253Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:59:04.256Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T22:59:04.256Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:01:14.660Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:01:14.663Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:01:14.663Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:03:24.924Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:03:24.927Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:03:24.927Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:05:35.160Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:05:35.163Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:05:35.164Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:07:46.152Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:07:46.155Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:07:46.156Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:09:56.352Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:09:56.356Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:09:56.356Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:12:07.387Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:12:07.390Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:12:07.390Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:14:17.615Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:14:17.618Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:14:17.618Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:16:27.803Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:16:27.806Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:16:27.806Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:18:38.691Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:18:38.694Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:18:38.695Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:20:49.753Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:20:49.759Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:20:49.760Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:23:00.745Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:23:00.747Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:23:00.748Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:25:11.555Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:25:11.558Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:25:11.558Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:27:22.454Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:27:22.460Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:27:22.461Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:29:32.652Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:29:32.657Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:29:32.657Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:31:42.919Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:31:42.922Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:31:42.922Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:33:52.907Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:33:52.910Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:33:52.911Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:36:03.711Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:36:03.714Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:36:03.714Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:38:13.940Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:38:13.943Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:38:13.944Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:40:24.305Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:40:24.307Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:40:24.308Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:42:34.580Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:42:34.583Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:42:34.583Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:44:44.805Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:44:44.810Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:44:44.811Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:46:55.947Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:46:55.950Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:46:55.951Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:49:06.557Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:49:06.561Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:49:06.566Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:51:16.819Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:51:16.822Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:51:16.823Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:53:27.199Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:53:27.202Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:53:27.203Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:55:37.403Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:55:37.406Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:55:37.406Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:57:47.614Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:57:47.617Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:57:47.617Z"}
{"message":"Unable to ensure uniqueness for usernames: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:59:57.767Z"}
{"message":"Unable to ensure uniqueness for user email addresses: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:59:57.770Z"}
{"message":"Unable to ensure uniqueness for role name: ","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [x.ziliao.link:27017] on first connect [MongoNetworkError: connection 0 to x.ziliao.link:27017 timed out]\n    at Pool.<anonymous> (/app/node_modules/mongodb-core/lib/topologies/server.js:562:11)\n    at Pool.emit (events.js:189:13)\n    at Pool.EventEmitter.emit (domain.js:441:20)\n    at Connection.<anonymous> (/app/node_modules/mongodb-core/lib/connection/pool.js:316:12)\n    at Object.onceWrapper (events.js:277:13)\n    at Connection.emit (events.js:189:13)\n    at Connection.EventEmitter.emit (domain.js:441:20)\n    at Socket.<anonymous> (/app/node_modules/mongodb-core/lib/connection/connection.js:256:10)\n    at Object.onceWrapper (events.js:277:13)\n    at Socket.emit (events.js:189:13)","errorLabels":["TransientTransactionError"],"level":"warn","timestamp":"2019-12-09T23:59:57.770Z"}
